version: '{branch}-{build}'
build: off
cache:
  - '%LOCALAPPDATA%\\pip\\Cache'

environment:

  matrix:
    # PYTHON 3.6
    - PYTHON: "C:\\Miniconda36"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "32"
      CONDA_PY: "36"
      CONDA_NPY: "142"

    - PYTHON: "C:\\Miniconda36-x64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
      CONDA_PY: "36"
      CONDA_NPY: "142"

    # PYTHON 3.7
    - PYTHON: "C:\\Miniconda37"
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "32"
      CONDA_PY: "37"
      CONDA_NPY: "142"

    - PYTHON: "C:\\Miniconda37-x64"
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "64"
      CONDA_PY: "37"
      CONDA_NPY: "142"

    # PYTHON 3.8
    - PYTHON: "C:\\Miniconda38"
      PYTHON_VERSION: "3.8"
      PYTHON_ARCH: "32"
      CONDA_PY: "38"
      CONDA_NPY: "142"

    - PYTHON: "C:\\Miniconda38-x64"
      PYTHON_VERSION: "3.8"
      PYTHON_ARCH: "64"
      CONDA_PY: "38"
      CONDA_NPY: "142"


install:
  # We need wheel installed to build wheels
  - ".build.cmd %PYTHON%\\python.exe -m pip install numpy psutil ninja"
  - ".build.cmd %PYTHON%\\python.exe -m pip install -r requirements-dev.txt"
  - ".build.cmd %PYTHON%\\python.exe setup.py build_ext --inplace"

test_script:
  - "set PYTHONPATH=."
  - ".build.cmd %PYTHON%\\python.exe blosc/test.py"
